### ISSUE TITLE
EGL could not initialize display

### ISSUE THREAD

**Issue by zehfernandes** [sergey-dryabzhinsky/qt-webkit-kiosk#13]
Hi,

I try run `qt-webkit-kiske` in raspberry using a buildroot distro and receive this error:

```EGL could not initialize display```

Someone has ideia what is going on?

**Comment by sergey-dryabzhinsky** [comment]
What Qt version use using?
How it was builded?
What was configure options?

**Comment by zehfernandes** [comment]
I used http://buildroot.uclibc.org/ with raspberry2_defconfig

with openEGL support and Qt5 version

**Comment by sergey-dryabzhinsky** [comment]
Try to follow that thread: https://www.raspberrypi.org/forums/viewtopic.php?f=53&t=79771
On RP2 device (paths may be different):
```
ls -l /usr/lib/qt/plugins/platforms/
```
If libqeglfs.so here:
```
ldd /usr/lib/qt/plugins/platforms/libqeglfs.so
```
If something not found - rebuild/reinstall system.

**Comment by sergey-dryabzhinsky** [comment]
Bought RP2. Trying to build root.
Did you build with mesa3d or rpi-userland EGL driver?

**Comment by sergey-dryabzhinsky** [comment]
Builded and started QWK: 
![imag0076](https://cloud.githubusercontent.com/assets/717597/9305379/b319b332-44f9-11e5-93cb-6462ca5d97ba.jpg)
Weird pic from my tv.

But keyboard not responding in QWK on RP2. Something still missing.

**Comment by sergey-dryabzhinsky** [comment]
Maybe some env vars from http://doc.qt.io/qt-5/embedded-linux.html

**Comment by sergey-dryabzhinsky** [comment]
I really recommend raspbian distro. It just works.

Maybe buildroot must be configured with evdev. But I done with it.
