### ISSUE TITLE
segfault when trying to load zdnet.com

### ISSUE THREAD

**Issue by SJLC** [sergey-dryabzhinsky/qt-webkit-kiosk#21]
Segfault occurs when progress bar gets to 89 or 90:

```
qt-webkit-kiosk -u http://zdnet.com
```

Both current master and the version installed from ppa (1.99.3-1sergey1~trusty1) have this same problem. Testing was done on x86_64 ubuntu xenial. I verified that the browsers in qtwebkit5-examples have no problem loading zdnet.com when running against the same qtwebkit, which is libqt5webkit5-5.5.1+dfsg-2ubuntu1 package from xenial.

This crash wins a prize for producing the largest backtrace I've ever seen, topping out at 44470 frames! There is a whole bunch of looping through the same 34 functions in the middle, but eventually it breaks out of the loop before it crashes.

[backtrace.zip](https://github.com/sergey-dryabzhinsky/qt-webkit-kiosk/files/344493/backtrace.zip)

**Comment by sergey-dryabzhinsky** [comment]
Please try latest code from `master`.
It should be more stable now.

**Comment by sergey-dryabzhinsky** [comment]
Yeah. Crashed with Qt 5.5 in CSS parser code.
Still working with Qt 4.8 but javascript hangs.

**Comment by sergey-dryabzhinsky** [comment]
Qwk with Qt 4.8 work only via debug build.

**Comment by sergey-dryabzhinsky** [comment]
Seems like I fixed in laster code from `master`.
Qt 4.8 build will alert about long running JS.
Qt 5.5 build will work fine.
I hope.

**Comment by SJLC** [comment]
Fixed with current master
