### ISSUE TITLE
I want to display chinese, how to config, Thanks

### ISSUE THREAD

**Issue by zhulinpinyu** [sergey-dryabzhinsky/qt-webkit-kiosk#26]

**Comment by sergey-dryabzhinsky** [comment]
It should display chinese symbols.
Or any unicode symbols.
![Снимок экрана_2020-02-20_23-50-39](https://user-images.githubusercontent.com/717597/74977536-ef21e100-543b-11ea-8d95-d9ef164186fd.png)
`./qt-webkit-kiosk -u "https://world.taobao.com"`

**Comment by zhulinpinyu** [comment]
@sergey-dryabzhinsky  thanks, I 've added chinese font in the OS sloved this
