### ISSUE TITLE
qt-webkit-kiosk fails to close

### ISSUE THREAD

**Issue by HED-jzignego** [sergey-dryabzhinsky/qt-webkit-kiosk#37]
When running the browser, I start it with start-stop-daemon in an init script. Sometimes I want to shut it down shortly after starting it, however about 10% of the time it fails to stop. I've enabled debugging output and I found that: this runs:
https://github.com/sergey-dryabzhinsky/qt-webkit-kiosk/blob/master/src/unixsignals.cpp#L107-L112

But the other end never sees it. So this never runs:
https://github.com/sergey-dryabzhinsky/qt-webkit-kiosk/blob/master/src/unixsignals.cpp#L114-L135

I can't seem to reproduce the issue on my desktop, only on my embedded device unfortunately.

So I found this documentation here: https://doc.qt.io/qt-5/unix-signals.html 

My question is thus: would you be willing to accept a PR that replaces most of unixsignals.cpp and socketpair.cpp with the simpler setup of just using SocketNotifier? I will write the PR if you are willing to accept it. 

This would eliminate the need for most of the code in both of those classes.

**Comment by sergey-dryabzhinsky** [comment]
Feel free to make a PR.

вт, 15 февр. 2022 г. в 01:03, HED-jzignego ***@***.***>:

**Comment by HED-jzignego** [comment]
Ok I will do that, can you merge this PR first: https://github.com/sergey-dryabzhinsky/qt-webkit-kiosk/pull/38, that does some prep work to get it ready for the real work.

**Comment by HED-jzignego** [comment]
I do have one question, the approach in https://doc.qt.io/qt-5/unix-signals.html uses AF_UNIX sockets, those are now supported in windows 10, is that good enough for windows support or do you want to support older versions of windows too even though they no longer are receiving security updates?
