### ISSUE TITLE
Browser Javascript Interval / Timeout hang if system time is set to the past

### ISSUE THREAD

**Issue by BluTiGeS** [sergey-dryabzhinsky/qt-webkit-kiosk#6]
Hi,
 I found out a issue if the system time of the local machine gets changed to the past for example 2 days back, a loop which is done via setInterval or setTimeout (Javascript) will stop working and the loop freezes.

I have read that this is a webkit issue, but not sure how to fix it. 
Can you please fix it in qt-webkit-kiosk?

**Comment by sergey-dryabzhinsky** [comment]
qt-webkit-kiosk is using Qt version of WebKit library.
So you should address to Qt team. Or even WebKit team.
And is not this is system issue? You should use NTP to synchronyze system and worldwide clocks.
