### ISSUE TITLE
Flash doesn't work

### ISSUE THREAD

**Issue by ozgureffe** [sergey-dryabzhinsky/qt-webkit-kiosk#7]
__Problem__ : Any flash content doesn't work. 
Shows this icon instead of flash content

![blue-lego](https://cloud.githubusercontent.com/assets/515248/6589239/8f69aa18-c7a5-11e4-9661-fd1b1b60c293.jpg)

* __Did I enable plugins in configuration file__ : yes
```
...
webgl=true
plugins=true
ignore_ssl_errors=true
...
```

* __Which version I am using__ : qt-webkit-kiosk-1.99.03-QT5.3.1.7z.exe

* __What is my OS__ : Win 7Ultimate 64Bit

* __Is flash plugins installed__ : Yes, they are working with Chrome and firefox but I did not do anything special for qt-webkit-kiosk

* __Did I modify anything__ : No, I am using as it is. Just a few parameters in configuration like `homepage` , `hide_mouse_cursor`

* __Did I miss something__ : ?

**Comment by sergey-dryabzhinsky** [comment]
Can you try 5.2 or 4.8 Qt version of QWK?

**Comment by sergey-dryabzhinsky** [comment]
You probably need to install 32bit flash plugin. Couse QWK is build in 32bit on Windows.

**Comment by sergey-dryabzhinsky** [comment]
Just checked. Sites with flash working.
Windows 7 64bit.
QWK 1.99.04 + Qt 5.5.
Installed Flash 18.0 for IE, FF, Chrome.
