### ISSUE TITLE
hide_mouse_cursor=true mouse cursor not directly hidden after load

### ISSUE THREAD

**Issue by BluTiGeS** [sergey-dryabzhinsky/qt-webkit-kiosk#9]
If the option hide_mouse_cursor=true is set in the config.ini, the mosue cursor is not directly hidden after page load. It gets hidden if interactions happens.

This looks ugly on startup.

qt-kiosk 1.99.03 + qt4.8.6 on ARM

**Comment by sergey-dryabzhinsky** [comment]
Done in https://github.com/sergey-dryabzhinsky/qt-webkit-kiosk/pull/12
New release - 1.99.4

**Comment by sergey-dryabzhinsky** [comment]
No response. Closing issue as resolved.
